import { SectionWrapper } from '@/components/sections/SectionWrapper'

export default function Privacy() {
  const lastUpdated = 'April 14, 2026'

  return (
    <div className="min-h-screen">
      <SectionWrapper dark id="privacy-hero">
        <div className="max-w-4xl">
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-heading font-bold text-brand-amber mb-4 uppercase tracking-tight">
            Privacy Policy
          </h1>
          <p className="text-sm text-brand-outline mb-12">Last updated: {lastUpdated}</p>

          <div className="space-y-8 text-brand-secondary leading-relaxed text-sm sm:text-base">
            <section>
              <h2 className="text-xl sm:text-2xl font-heading font-semibold text-foreground mb-3">1. Overview</h2>
              <p>
                SaaSless Forge LLC ("SaaSless Forge," "we," "us," or "our") respects your privacy. This Privacy Policy describes
                how we collect, use, and safeguard information when you engage us for custom software development, use any of
                our applications, or communicate with us.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-heading font-semibold text-foreground mb-3">2. Information We Collect</h2>
              <p className="mb-3">We collect information you provide directly to us, including:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Contact information such as your name, business name, email address, and mailing address.</li>
                <li>
                  Mobile phone numbers that you voluntarily provide to us for project communications, service notifications,
                  and SMS-based features of the software we build for you.
                </li>
                <li>Billing information processed through our payment provider (Stripe).</li>
                <li>Project requirements, files, and data you share with us during engagements.</li>
                <li>Basic usage and device information collected automatically when you visit saaslessforge.com.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-heading font-semibold text-foreground mb-3">3. How We Use Your Information</h2>
              <p className="mb-3">We use the information we collect to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Deliver the custom software and services you have engaged us to provide.</li>
                <li>Send you operational communications including project status updates, deployment notifications, billing notices, and responses to your inquiries.</li>
                <li>Send you SMS messages when you have opted in — for example, appointment reminders, "on my way" notifications, and service alerts generated by applications we build.</li>
                <li>Invoice and collect payment for services rendered.</li>
                <li>Maintain the security, integrity, and functionality of our websites and applications.</li>
                <li>Comply with our legal obligations.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-heading font-semibold text-foreground mb-3">4. SMS and Mobile Information</h2>
              <p className="mb-3">
                When you provide a mobile phone number to SaaSless Forge or to an application we operate, you may receive SMS
                messages relating to your engagement or the service you have signed up for. Every marketing or recurring
                message includes clear opt-out instructions. You may opt out at any time by replying <strong>STOP</strong> to any
                message, and you may reply <strong>HELP</strong> to receive help. Message and data rates may apply. Message
                frequency varies.
              </p>
              <p className="font-semibold text-foreground">
                Mobile information (including phone numbers and consent records) will not be shared with third parties or
                affiliates for marketing or promotional purposes. No mobile information will be shared with third parties or
                affiliates for marketing or promotional purposes. All the above categories exclude text messaging originator
                opt-in data and consent; this information will not be shared with any third parties.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-heading font-semibold text-foreground mb-3">5. Third-Party Service Providers</h2>
              <p className="mb-3">
                We use carefully selected third parties to operate our business. These include:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Twilio</strong> — delivery of SMS messages on our behalf and on behalf of the applications we build.</li>
                <li><strong>Stripe</strong> — processing of invoices and payments.</li>
                <li><strong>Render, Netlify, Vercel</strong> — hosting of our websites and client applications.</li>
                <li><strong>Cloudflare R2</strong> — secure file storage.</li>
                <li><strong>SendGrid</strong> — transactional email delivery.</li>
              </ul>
              <p className="mt-3">
                These providers process data only as needed to perform their services for us and are contractually bound to
                protect your information. We do not sell, rent, or trade your personal information.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-heading font-semibold text-foreground mb-3">6. Data Security</h2>
              <p>
                We employ industry-standard administrative, technical, and physical safeguards to protect your information.
                No method of electronic transmission or storage is perfectly secure, but we make reasonable efforts to protect
                the confidentiality and integrity of any information you entrust to us.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-heading font-semibold text-foreground mb-3">7. Data Retention and Deletion</h2>
              <p>
                We retain your information for as long as your engagement with SaaSless Forge is active and for a reasonable
                period thereafter to comply with tax, accounting, and legal obligations. You may request deletion of your
                personal information at any time by emailing us at hello@saaslessforge.com. We will honor verified deletion
                requests within thirty (30) days, subject to legal record-keeping requirements.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-heading font-semibold text-foreground mb-3">8. Your Rights</h2>
              <p>
                Depending on your jurisdiction, you may have the right to access, correct, delete, or restrict the use of your
                personal information, and to opt out of certain communications. To exercise any of these rights, contact us at
                hello@saaslessforge.com.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-heading font-semibold text-foreground mb-3">9. Children's Privacy</h2>
              <p>
                Our services are not directed to children under 13. We do not knowingly collect personal information from
                children. If you believe we have collected information from a child, please contact us and we will promptly
                delete it.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-heading font-semibold text-foreground mb-3">10. Changes to This Policy</h2>
              <p>
                We may update this Privacy Policy from time to time. The "Last updated" date at the top of this page reflects
                the date of the most recent revision. Material changes will be communicated via email or a notice on our
                website.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-heading font-semibold text-foreground mb-3">11. Contact Us</h2>
              <p>
                Questions about this Privacy Policy or our data practices should be directed to:<br />
                SaaSless Forge LLC<br />
                Email: <a href="mailto:hello@saaslessforge.com" className="text-brand-amber hover:underline">hello@saaslessforge.com</a>
              </p>
            </section>
          </div>
        </div>
      </SectionWrapper>
    </div>
  )
}
